### ISSUE TITLE
query returns the prompt and document?

### ISSUE THREAD

**Issue by hemanth** [embedchain/embedchain#1323]
### 🐛 Describe the bug

<img width="1400" alt="image" src="https://github.com/embedchain/embedchain/assets/18315/eccbdf10-4c9c-4f4a-89b8-23e53a0fb83c">

```py
import os
# Replace this with your HF token
os.environ["HUGGINGFACE_ACCESS_TOKEN"] = ""

from embedchain import App

config = {
  'llm': {
    'provider': 'huggingface',
    'config': {
      'model': 'mistralai/Mistral-7B-Instruct-v0.2',
      'top_p': 0.5
    }
  },
  'embedder': {
    'provider': 'huggingface',
    'config': {
      'model': 'sentence-transformers/all-mpnet-base-v2'
    }
  }
}
app = App.from_config(config=config)
app.add("https://www.forbes.com/profile/elon-musk")
app.add("https://en.wikipedia.org/wiki/Elon_Musk")
app.query("What is the net worth of Elon Musk today?")
```

**Comment by deshraj** [comment]
Hey @hemanth, thanks for opening the issue. What you are seeing on your notebook are some debug statements and not the returned values from the functions. 

Although I think it's a good callout for us to make these logger.info() rather than keeping them as print statements.

Closing this issue for now.

**Comment by hemanth** [comment]
Ah! I see.

The debug statements are getting assigned as well? 🤔 

<img width="1253" alt="image" src="https://github.com/embedchain/embedchain/assets/18315/bbd00903-2e7f-4541-a710-6d4e7dfc5847">
