### ISSUE TITLE
Response from other websites 

### ISSUE THREAD

**Issue by SuhasPalani** [embedchain/embedchain#1378]
### 🐛 Describe the bug

import os

from embedchain import App
from api import api_key

os.environ["OPENAI_API_KEY"] = api_key
# print(os.environ["OPENAI_API_KEY"])

app = App()

app.add("https://www.alislam.org/quran/Holy-Quran-English.pdf")
app.add("http://triggs.djvu.org/djvu-editions.com/BIBLES/DRV/Download.pdf")
app.add("https://scholar.archive.org/work/vhyqfoxpjfd2tf5xf5e26nd3si/access/wayback/http://www.bhagavatgita.ru/files/Bhagavad-gita_As_It_Is.pdf")

print(app.query(where is chicago"))

#answer- Chicago is a city located in the state of Illinois, in the United States.

What I observed is, I had to get a response from the particular webiste, but it is scraping information from others too

**Comment by deshraj** [comment]
Hey @SuhasPalani, it looks that these website might be blocking the scraping and hence you are not able to fetch the information. You can either use their APIs (if they offer) or try passing extra headers like user-agent to mimick the browser behavior. 

Closing this issue for now since this is not an issue in the Embedchain package.
