### ISSUE TITLE
feature request: add support for plain text documents, word documents, RTF

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#142]
- opened on behalf of [twitter user Singh316Singh](https://twitter.com/Singh316Singh/status/1676599116292341761)

**Comment by taranjeet** [comment]
word docs support is already added by @sahilyadav902

**Comment by cachho** [comment]
Yes, and plain text loading is one of these things. Realitically, you will get better results if you load the file yourself, and then embed it with `add`, using the `text` loader. Because that gives you the choice to decide whether you want to split lines or do the chunker do the work on the whole file. Different use cases exist, and this really isn't too much work to get the most flexibility.

**Comment by deshraj** [comment]
We support the first two document types i.e plain text and word documents. Will close the issue for now since no one has requested for rtf format after 2023.
