### ISSUE TITLE
[Clarification] Configure the chunking strategy / configure how many context to use when querying LLM?

### ISSUE THREAD

**Issue by vpinigin** [embedchain/embedchain#351]
Hi,
while playing with your library, I've come with some question which would be quite useful to understand.

1) Can we use custom text splitters from langchain library? where are different text splitters strategies and using recursive on is quite limited for more tricky task?
2) What is the difference between `add_local ` and  `add` in terms of `text` formats? two methods which seems to do the same and are quite confusing for having two different names, I think one of it should be deprecated?
3) Can we add verbosity paramater for `add` method? now when I add multiple text datasets into a loop, I get printed back the whole original text which makes make printout quite messy for big texts. Also it will be quite great to have a configuration to print how the original text was chunked based on chunking strategy. 

4) Is there any way to control when quering LLM how many context to give (I assume to configure the distance between vectors) ?

**Comment by cachho** [comment]
> What is the difference between add_local  and add in terms of text formats? two methods which seems to do the same and are quite confusing for having two different names, I think one of it should be deprecated?

It's the same, the only difference is that the argument is called `url` or `content` #320 

> Can we add verbosity paramater for add method? now when I add multiple text datasets into a loop, I get printed back the whole original text which makes make printout quite messy for big texts. Also it will be quite great to have a configuration to print how the original text was chunked based on chunking strategy.

I've been wanting to do this for a while #109, but I guess some people really like their prints (I don't). 

> Is there any way to control when quering LLM how many context to give (I assume to configure the distance between vectors) ?

Number of documents is available as a QueryConfig/ChatConfig option, someone deleted it from the documentation for some reason.  `:param number_documents: Number of documents to pull from the database as context.` - it's always a set number, I have had the idea to limit the range too, I just don't know exactly how to do it or what I would set it at, should it be a set maximum, or should it be a certain factor, compared to the nearest neighbor (so e.g. document 2 can only be 2x as distant as document 1, otherwise you only  only get one).

**Comment by cachho** [comment]
This part `:param number_documents: Number of documents to pull from the database as context.` has been added back to the documentation. Closing this for now. Please reopen if you need more clarification.
