### ISSUE TITLE
feature request: add support for elasticsearch as a datasource

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#386]
### 🚀 The feature

Deliverables:

- Add support for storing the data into elasticsearch
- User will specify the db while instantiating the class. Eg:

##### Using elasticsearch as a datasource
```python
from embedchain import App

app = App(db="es")
```

##### Using chroma as a datasource
```python
from embedchain import App

app = App(db="chroma")
```

- If no datasource is specified, we will default to chroma db by default
- Make sure that `app.query()` works as intended and should return reasonable response

### Motivation, pitch

Currently, embedchain only supports chroma db as the data source. We want to extend the support to have more vector databases. We want to start by adding support for elasticsearch.

**Comment by cachho** [comment]
I think we should rethink the whole database integration. Since we already have a `BaseVectorDb` class with subclasses, we should abstract where possible, and only expose streamlined, widely supported methods to the main class, such as ``initialize, `add` and `delete`, `reset`/`delete_all`, with filter options and metadata.
