### ISSUE TITLE
Support OpenAI models via Azure deployments 

### ISSUE THREAD

**Issue by wxp16** [embedchain/embedchain#770]
### 🚀 The feature

Support OpenAI models via Azure deployments 

### Motivation, pitch

We don't have key of directly accessing the openai models.

**Comment by deshraj** [comment]
Hey @wxp16, this issue is already resolved. We have also added a jupyter notebook for you to test the Azure OpenAI integration with Embedchain: https://github.com/embedchain/embedchain/blob/main/notebooks/azure-openai.ipynb

You can find the docs for OpenAI Azure integration here: https://docs.embedchain.ai/components/llms#azure-openai
